# Canonical development and automation entry points for AWK Minifier.

SHELL := /bin/bash
.SHELLFLAGS := -eu -o pipefail -c

DIST_DIR := dist
DIST_DEV_SCRIPT := $(DIST_DIR)/awk-minifier.dev.awk
DIST_SCRIPT := $(DIST_DIR)/awk-minifier.awk
DIST_MIN_SCRIPT := $(DIST_DIR)/awk-minifier.min.awk
DIST_SCRIPTS := $(DIST_DEV_SCRIPT) $(DIST_SCRIPT) $(DIST_MIN_SCRIPT)
DIST_CHECKSUMS := $(addsuffix .sha256,$(DIST_SCRIPTS))
SOURCE_FILES := src/diagnostics.awk src/output.awk src/lexer.awk src/main.awk

VENDOR_DIR := vendor
DEPENDENCY_MANIFEST := dependencies.txt
STANDARDS_MANIFEST := dependencies-standards.txt
STANDARDS_ROOT := doc/standards
BASHDEPS := $(VENDOR_DIR)/bashdeps.bash
BASHDEPS_VERSION := 0.0.6
BASHDEPS_URL := https://github.com/wesley-dean/bashdeps/releases/download/v$(BASHDEPS_VERSION)/bashdeps.bash
BASHDEPS_SHA256 := bb6c807fa12c010950bda06172ac0611d278c57aca1f8352f41502d0d76b4e6c
DOXYGEN_AWK_FILTER := $(VENDOR_DIR)/doxygen-awk.awk
ADRCTL := $(VENDOR_DIR)/adrctl.bash
ADR_DIR := doc/adr
ADR_INDEX_INTRO := $(ADR_DIR)/README.intro.md
ADR_INDEX_OUTRO := $(ADR_DIR)/README.outro.md
ADR_INDEX_FILE := $(ADR_DIR)/README.md
REFERENCE_DOC_DIR := doc/reference

AWK_BIN ?= awk
VERSION ?= $(shell git describe --tags --always 2>/dev/null || printf '0.0.0-dev')
BUILD_COMMIT ?= $(shell git rev-parse --short=12 HEAD 2>/dev/null || printf 'unknown')
BUILD_DATE ?= $(shell git show -s --format=%cI HEAD 2>/dev/null || printf 'unknown')

.PHONY: all adr-index build check checksums clean deps deps-check distclean docs docs-clean FORCE standards standards-check test verify-bashdeps

all: deps
	$(MAKE) --no-print-directory build

build: $(DIST_SCRIPTS) $(DIST_CHECKSUMS)

$(DIST_DEV_SCRIPT): $(SOURCE_FILES)
	@mkdir -p "$(DIST_DIR)"
	@{ \
		printf '%s\n' '#!/usr/bin/awk -f'; \
		printf '%s\n' '# Generated by make build. Do not edit directly.'; \
		printf '%s\n' '# Artifact: development'; \
		printf '%s\n' '# Version: $(VERSION)'; \
		printf '%s\n' '# Build date: $(BUILD_DATE)'; \
		printf '%s\n' '# Build commit: $(BUILD_COMMIT)'; \
		printf '%s\n' '# Source files: $(SOURCE_FILES)'; \
		printf '\n'; \
		cat $(SOURCE_FILES); \
	} >"$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

# The ordinary artifact removes only the project's Doxygen documentation lines.
# It deliberately does not attempt general AWK comment stripping.
$(DIST_SCRIPT): $(DIST_DEV_SCRIPT)
	@sed '/^##/d' "$<" >"$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

# Bootstrap rule: until a previous released AWK Minifier is pinned through
# bashdeps, the stable .min.awk release slot is byte-for-byte identical to the
# development artifact.  ADR-019 governs the later transition.
$(DIST_MIN_SCRIPT): $(DIST_DEV_SCRIPT)
	@cp "$<" "$@.tmp"
	@chmod 0755 "$@.tmp"
	@mv "$@.tmp" "$@"

$(DIST_DIR)/%.awk.sha256: $(DIST_DIR)/%.awk
	@digest=''; \
	if command -v sha256sum >/dev/null 2>&1; then \
		digest="$$(sha256sum "$<" | awk '{print $$1}')"; \
	elif command -v shasum >/dev/null 2>&1; then \
		digest="$$(shasum -a 256 "$<" | awk '{print $$1}')"; \
	else \
		printf '%s\n' 'No SHA-256 command is available for build checksums' >&2; \
		exit 1; \
	fi; \
	printf '%s  %s\n' "$$digest" "$(notdir $<)" >"$@.tmp"; \
	mv "$@.tmp" "$@"

checksums: build

check:
	@$(AWK_BIN) $(foreach source,$(SOURCE_FILES),-f $(source)) </dev/null >/dev/null

test: build
	@AWK_BIN="$(AWK_BIN)" tests/run-tests.sh

FORCE:

$(BASHDEPS): FORCE
	@mkdir -p "$(VENDOR_DIR)"
	@verify_hash() { \
		path=$$1; \
		if command -v sha256sum >/dev/null 2>&1; then \
			printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$$path" | sha256sum -c - >/dev/null 2>&1; \
		elif command -v shasum >/dev/null 2>&1; then \
			actual="$$(shasum -a 256 "$$path" | awk '{print $$1}')"; \
			[[ "$$actual" == "$(BASHDEPS_SHA256)" ]]; \
		else \
			return 2; \
		fi; \
	}; \
	if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	if [[ -f "$@" ]] && verify_hash "$@"; then \
		chmod 0755 "$@"; \
		exit 0; \
	fi; \
	if ! command -v curl >/dev/null 2>&1; then \
		printf '%s\n' 'curl is required to bootstrap bashdeps.bash' >&2; \
		exit 1; \
	fi; \
	tmp="$@.tmp"; \
	trap 'rm -f "$$tmp"' EXIT; \
	curl -fsSL "$(BASHDEPS_URL)" -o "$$tmp"; \
	if ! verify_hash "$$tmp"; then \
		printf '%s\n' 'Downloaded bashdeps.bash does not match the committed SHA-256 digest' >&2; \
		exit 1; \
	fi; \
	chmod 0755 "$$tmp"; \
	mv "$$tmp" "$@"; \
	trap - EXIT

verify-bashdeps:
	@test -x "$(BASHDEPS)" || { printf '%s\n' 'Missing or non-executable bashdeps bootstrap; run make deps' >&2; exit 1; }
	@if command -v sha256sum >/dev/null 2>&1; then \
		printf '%s  %s\n' "$(BASHDEPS_SHA256)" "$(BASHDEPS)" | sha256sum -c - >/dev/null 2>&1 || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps' >&2; exit 1; }; \
	elif command -v shasum >/dev/null 2>&1; then \
		actual="$$(shasum -a 256 "$(BASHDEPS)" | awk '{print $$1}')"; \
		[[ "$$actual" == "$(BASHDEPS_SHA256)" ]] || { printf '%s\n' 'bashdeps.bash digest mismatch; run make deps' >&2; exit 1; }; \
	else \
		printf '%s\n' 'No SHA-256 verification command is available for bashdeps.bash' >&2; exit 1; \
	fi

deps: $(BASHDEPS) $(DEPENDENCY_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync "$(DEPENDENCY_MANIFEST)"

deps-check: verify-bashdeps $(DEPENDENCY_MANIFEST)
	"$(BASHDEPS)" verify "$(DEPENDENCY_MANIFEST)"

standards: $(BASHDEPS) $(STANDARDS_MANIFEST)
	$(MAKE) --no-print-directory verify-bashdeps
	"$(BASHDEPS)" sync --dest-root "$(STANDARDS_ROOT)" "$(STANDARDS_MANIFEST)"

standards-check: verify-bashdeps $(STANDARDS_MANIFEST)
	"$(BASHDEPS)" verify --dest-root "$(STANDARDS_ROOT)" "$(STANDARDS_MANIFEST)"

adr-index:
	@test -f "$(ADRCTL)" || { printf '%s\n' 'Missing vendor/adrctl.bash; run make deps or make all' >&2; exit 1; }
	@tmp="$(ADR_INDEX_FILE).tmp"; trap 'rm -f "$$tmp"' EXIT; \
	bash "$(ADRCTL)" generate toc -i "$(ADR_INDEX_INTRO)" >"$$tmp"; \
	printf '\n' >>"$$tmp"; cat "$(ADR_INDEX_OUTRO)" >>"$$tmp"; \
	mv "$$tmp" "$(ADR_INDEX_FILE)"; trap - EXIT

docs: adr-index
	@test -f "$(DOXYGEN_AWK_FILTER)" || { printf '%s\n' 'Missing vendor/doxygen-awk.awk; run make deps or make all' >&2; exit 1; }
	@command -v doxygen >/dev/null 2>&1 || { printf '%s\n' 'doxygen is required for make docs' >&2; exit 1; }
	doxygen Doxyfile

docs-clean:
	rm -rf "$(REFERENCE_DOC_DIR)"
	rm -f "$(ADR_INDEX_FILE)" "$(ADR_INDEX_FILE).tmp"

clean: docs-clean
	rm -rf "$(DIST_DIR)" test-results

distclean: clean
	rm -rf "$(VENDOR_DIR)"
